# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc1d2230199f3aa4c87d59d4231de5c6713496e6a1bc9ae5aa32ea9fc929ab419fc37a8cc631c6f3de0be70a656c629ffa5312705d51b181cc992599fb8c9e40

test:
  secret_key_base: 92982e4ba1ad25af0704894715ee19925984f42499b80b15cad74b3c6318ca286a30ff8d49e78d27240ce173e0509f9922fe4629c058980fb22dfd3ba992850c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4dc81022dfd1bc8af92d99f16b0a7ff87d39a9d01fe5d17f2cb7327de896fb624efe810be370c8ed51543f1006b16be928f7179a481b5c829777875a377a0f7f
